[package]
name = "shiba-sql-frontend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
sha2 = "0.10"
shiba-compiler = { path = "../shiba-compiler" }
shiba-protocol = { path = "../shiba-protocol" }
sqlparser = { version = "=0.62.0", default-features = false, features = ["std"] }

[dev-dependencies]
shiba-operator = { path = "../shiba-operator" }

[lints]
workspace = true
